/**************************************************************************************************
 * Name: Live800Flag
 * Object: ***
 * Purpose: ***
 * Author: Vicia Wang (vicia.hh.wang@cn.pwc.com)
 * Create Date: 2016-05-10
 * Modified History:
 * 2016-05-10    Allen    Format the code
***************************************************************************************************/
public class Live800Flag {

    public Static Boolean isTestPrepToCounselling = false;
    public Static Boolean isCounsellingToTestPrep = false;
}