public class RecordTypeRelated {
   public static String  FrontDeskVisit_App='012280000009rO9AAI';
   public static String  Invitation_App='012280000009e0GAAQ';
   public static String  Assignment_App='012280000009e0LAAQ';
   public static String  Reminder_App='012280000009e0QAAQ';
   public static String  Follow_Up_FlW='012280000009fEaAAI';
   public static String  Telecommunication_FlW='012280000009fEQAAY';
   public static String  Counselling_Opp='012280000009b2RAAQ';
   public static String  TestPrep_Opp='012280000009b2SAAQ';
   public static String  ScholarTree_Opp='012280000009n5ZAAQ';
   public static String  New_Pathway_Opp='012280000009tGQAAY';
   public static String  SubAgent_Opp='01228000000A1WPAA0';
   public static String  Opportunity_Status_ALog='012280000009ckqAAA';
   public static String  Xueyou_Opportunity_Status_ALog='01228000000AFHrAAO';
   public static String  Level_4_Promotion_Channel_Camp='012280000009fDSAAY';
   public static Set<String> Opportunity_approval_logs_record_types = new Set<String>{Opportunity_Status_ALog, Xueyou_Opportunity_Status_ALog};
}