/**************************************************************************************************
 * Name: TriggerShouldRun
 * Object: ***
 * Purpose: ***
 * Author: Vicia Wang (vicia.hh.wang@cn.pwc.com)
 * Create Date: 2016-05-10
 * Modified History:
 * 2016-05-10    Allen    Format the code
***************************************************************************************************/
public with sharing class TriggerShouldRun {

    public static Boolean AppointmentShouldRun = true;
    public static Boolean leadShouldRun = true;
}